---
- name: Create galaxy.ini file for lite start
  copy:
    src: '{{ galaxy_config_path }}/galaxy.ini.sample'
    dest: '{{ galaxy_config_path }}/galaxy.ini.lite'
    remote_src: true

- name: edit galaxy.ini.lite
  ini_file:
    dest: '{{ galaxy_config_path}}/galaxy.ini.lite'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - { section: 'app:main', option: 'database_connection', value: '{{ galaxy_database_connection }}' }
    - { section: 'app:main', option: 'install_database_connection', value: '{{ galaxy_install_database_connection }}' }
    - { section: 'app:main', option: 'admin_users', value: '{{ GALAXY_ADMIN_EMAIL }}' }
