---
- set_fact:
    galaxyctl_bin_path: '/usr/bin'
  when: ansible_os_family == "RedHat"

- set_fact:
    galaxyctl_bin_path: '/usr/local/bin'
  when: ansible_os_family == "Debian"

- set_fact:
    galaxyctl_path: '{{ galaxy_FS_path }}/.galaxyctl'

- name: 'Update/Clone Galaxy Central Management Tool (galaxyctl) repository'
  git:
    repo: 'https://github.com/Laniakea-elixir-it/galaxyctl.git'
    version: devel
    clone: yes
    update: yes
    dest: '{{ galaxyctl_path }}'

- name: Update galaxyctl
  pip:
    name: .
    chdir: '{{ galaxyctl_path }}'
    extra_args: --ignore-installed
  become_user: root
  become_method: sudo

#- name: Edit galaxyctl ini file
#  ini_file:
#    dest: '/etc/galaxyctl/galaxyctl.ini'
#    section: '{{ item.section }}'
#    option: '{{ item.option }}'
#    value: '{{ item.value }}'
#  with_items:
#    - { section: 'galaxy', option: 'init_system', value: '{{ init_type }}' }          
#    - { section: 'galaxy', option: 'supervisord_conf_file', value: '{{ supervisord_conf_path }}/supervisord.conf' }
#    - { section: 'galaxy', option: 'galaxy_config_file', value: '{{ galaxy_config_file }}' }      
#    - { section: 'galaxy', option: 'uwsgi_pid_file', value: '{{ galaxy_log_path }}/uwsgi.pid' }
#    - { section: 'galaxy', option: 'galaxyctl_log_file', value: '{{ galaxy_log_path }}/galaxyctl.log' }
#  become_user: root
#  become_method: sudo

- name: Create api virtual environment
  pip:
    requirements: '{{ galaxyctl_path }}/api/requirements.txt'
    virtualenv: '{{ galaxyctl_path }}/api/venv'

- name: Copy systemd unit file
  copy:
    src: '{{ galaxyctl_path }}/api/gunicorn/galaxyctl-api.service'
    dest: '/etc/systemd/system/galaxyctl-api.service'
    remote_src: yes
  become_user: root
  become_method: sudo

- name: Start and enable ggalaxyyctl_api
  service:
    name: galaxyctl-api
    state: started
    enabled: yes
  become_user: root
  become_method: sudo

- name: Add galaxyctl_api to nginx.conf
  blockinfile:
    dest: /etc/nginx/nginx.conf
    insertbefore: "error_page   500 502 503 504  /50x.html;"
    block: |4
                location /galaxyctl_api {
                    proxy_read_timeout 300;
                    proxy_set_header Host $http_host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                    proxy_pass http://127.0.0.1:5001;
                }
  become_user: root
  become_method: sudo
