---
# Workflows are installed at user level so we install it in the administrator account.

- name: Get Galaxy flavor recipes
  git:
    repo: 'https://github.com/indigo-dc/Galaxy-flavors-recipes.git'
    clone: yes
    force: yes
    dest: '/tmp/Galaxy-flavors-recipes'

- name: Include sources list
  include: '/tmp/Galaxy-flavors-recipes/{{galaxy_flavor}}/{{galaxy_flavor}}-sources-list.yml'

- name: Create/invoke script virtualenv
  pip:
    name: '{{ item }}'
    virtualenv: '/tmp/venv'
    virtualenv_command: "{{ pip_virtualenv_command | default( 'virtualenv' ) }}"
    state: forcereinstall
  with_items:
    - ephemeris==0.7.0

- include: install_workflow_list.yml
  with_items: '{{ galaxy_tools_workflow_list_path }}'
  loop_control:
    loop_var: workflow_list_path
  when:
    - install_workflows|bool
