---
# PostgreSQL configration recipe

#______________________________________
# CentOS 7

- include: postgresql_redhat.yml
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat"

#______________________________________
# Ubuntu

- include: postgresql_ubuntu.yml
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"
