---
# Add ssh key for galaxy and root user
- name: 'Inject ssh public key - {{ galaxy_user }}'
  authorized_key:
    user: '{{ galaxy_user }}'
    key: '{{ galaxy_instance_key_pub }}'
  become: true
  become_user: '{{ galaxy_user }}'
  register: authorized_key_galaxy_user_result
  failed_when: ('invalid key specified' in authorized_key_galaxy_user_result.stderr)
  ignore_errors: true

- name: 'Inject ssh public key - root'
  authorized_key:
    user: 'root'
    key: '{{ galaxy_instance_key_pub }}'
  register: authorized_key_root_result
  failed_when: ('invalid key specified' in authorized_key_root_result.stderr)
  ignore_errors: true
