---
- name: Include uWSGI specific variables.
  include_vars: uwsgi_vars.yml

#______________________________________
# Edit uWSGI section in galaxy.yml or galaxy.ini file
- include: uwsgi_{{when: galaxy_config_style}}.yml

#______________________________________
### job_conf section
# Edit job_conf.xml file

- include: job_conf.yml
