---
- name: Include uWSGI specific variables.
  include_vars: uwsgi_vars.yml

#______________________________________
# Add uWSGI section to galaxy.ini file
# Galaxy < release_18.01

- include: uwsgi_ini.yml
  when: galaxy_config_file_extension == 'ini'

#______________________________________
# Edit uWSGI section in galaxy.tyml file
# Galaxy >= release_18.05

- include: uwsgi_yaml.yml
  when: galaxy_config_file_extension == 'yml'

#______________________________________
### job_conf section
# Edit job_conf.xml file

- include: job_conf.yml
